"""create new users log table

Revision ID: 560a0e51ddc2
Revises: 699c588ce924
Create Date: 2024-02-23 17:53:38.875993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560a0e51ddc2'
down_revision = '699c588ce924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_log_id', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reading_log_id'], ['reading_logs.id'], name=op.f('fk_user_logs_reading_log_id_reading_logs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    # ### end Alembic commands ###
